"""
config.py — RWA Infinity Model v1.0
Complete Real World Asset universe, risk tiers, API config.
"""

# ─── API Endpoints (all free / public) ────────────────────────────────────────
DEFILLAMA_BASE      = "https://api.llama.fi"
DEFILLAMA_YIELDS    = "https://yields.llama.fi"
COINGECKO_BASE      = "https://api.coingecko.com/api/v3"
RWA_XYZ_BASE        = "https://app.rwa.xyz"          # scrape / public data
ETHERSCAN_BASE      = "https://api.etherscan.io/api"
POLYGONSCAN_BASE    = "https://api.polygonscan.com/api"

# ─── HTTP Config ───────────────────────────────────────────────────────────────
REQUEST_TIMEOUT     = 15   # seconds
MAX_RETRIES         = 3
RETRY_BACKOFF       = 1.5  # exponential back-off multiplier

# ─── Scheduler ────────────────────────────────────────────────────────────────
REFRESH_INTERVAL_MINUTES = 60   # full data refresh every hour
PRICE_INTERVAL_SECONDS   = 300  # price-only refresh every 5 min
NEWS_INTERVAL_MINUTES    = 30   # news sentiment refresh

# ─── Database ─────────────────────────────────────────────────────────────────
DB_FILE = "rwa_model.db"

# ─── Anthropic ────────────────────────────────────────────────────────────────
CLAUDE_MODEL    = "claude-sonnet-4-6"
CLAUDE_TIMEOUT  = 45.0
AI_CACHE_TTL    = 1800   # 30 min

# ─────────────────────────────────────────────────────────────────────────────
# COMPLETE RWA ASSET UNIVERSE
# Each asset: id, name, category, subcategory, chain, protocol, token_symbol,
#             coingecko_id, defillama_slug, expected_yield_pct, risk_score (1-10),
#             liquidity_score (1-10), regulatory_score (1-10), description
# ─────────────────────────────────────────────────────────────────────────────

RWA_UNIVERSE = [

    # ── TOKENIZED US TREASURIES & GOVERNMENT BONDS ──────────────────────────
    {
        "id": "BUIDL",
        "name": "BlackRock USD Institutional Digital Liquidity Fund",
        "category": "Government Bonds",
        "subcategory": "US Treasury",
        "chain": "Ethereum",
        "protocol": "BlackRock / Securitize",
        "token_symbol": "BUIDL",
        "coingecko_id": None,
        "defillama_slug": "blackrock-buidl",
        "expected_yield_pct": 5.10,
        "risk_score": 1,
        "liquidity_score": 7,
        "regulatory_score": 10,
        "min_investment_usd": 5_000_000,
        "inception_date": "2024-03-20",
        "description": "BlackRock's tokenized money market fund backed by US Treasury bills. Institutional grade, $100+ billion AUM manager.",
        "tags": ["institutional", "treasury", "money-market", "accredited"],
    },
    {
        "id": "BENJI",
        "name": "Franklin OnChain US Government Money Fund",
        "category": "Government Bonds",
        "subcategory": "US Treasury",
        "chain": "Stellar / Polygon",
        "protocol": "Franklin Templeton",
        "token_symbol": "BENJI",
        "coingecko_id": None,
        "defillama_slug": "franklin-benji",
        "expected_yield_pct": 5.05,
        "risk_score": 1,
        "liquidity_score": 8,
        "regulatory_score": 10,
        "min_investment_usd": 0,
        "inception_date": "2021-04-04",
        "description": "First US-registered fund to use public blockchain for transaction processing. US govt securities + overnight repos.",
        "tags": ["retail", "treasury", "money-market", "registered-fund"],
    },
    {
        "id": "USTB",
        "name": "Superstate Short Duration US Government Securities Fund",
        "category": "Government Bonds",
        "subcategory": "US Treasury",
        "chain": "Ethereum",
        "protocol": "Superstate",
        "token_symbol": "USTB",
        "coingecko_id": "superstate-short-duration-us-government-securities-fund",
        "defillama_slug": "superstate",
        "expected_yield_pct": 5.08,
        "risk_score": 1,
        "liquidity_score": 8,
        "regulatory_score": 9,
        "min_investment_usd": 100_000,
        "inception_date": "2023-08-01",
        "description": "SEC-registered 40-Act fund tokenized on Ethereum. Direct competitor to BUIDL with broader access.",
        "tags": ["institutional", "treasury", "registered-fund", "sec"],
    },
    {
        "id": "TBILL",
        "name": "OpenEden T-Bill Vault",
        "category": "Government Bonds",
        "subcategory": "US Treasury",
        "chain": "Ethereum",
        "protocol": "OpenEden",
        "token_symbol": "TBILL",
        "coingecko_id": "openeden-tbill",
        "defillama_slug": "openeden",
        "expected_yield_pct": 5.12,
        "risk_score": 2,
        "liquidity_score": 9,
        "regulatory_score": 8,
        "min_investment_usd": 100_000,
        "inception_date": "2023-01-10",
        "description": "24/7 T-bill yield vault with daily liquidity. Licensed in Singapore, backed by US short-duration Treasuries.",
        "tags": ["institutional", "treasury", "defi-native", "singapore"],
    },
    {
        "id": "OUSG",
        "name": "Ondo Short-Term US Government Bond Fund",
        "category": "Government Bonds",
        "subcategory": "US Treasury",
        "chain": "Ethereum / Polygon / Solana",
        "protocol": "Ondo Finance",
        "token_symbol": "OUSG",
        "coingecko_id": "ondo-us-dollar-yield",
        "defillama_slug": "ondo-finance",
        "expected_yield_pct": 5.02,
        "risk_score": 2,
        "liquidity_score": 9,
        "regulatory_score": 9,
        "min_investment_usd": 100_000,
        "inception_date": "2023-01-04",
        "description": "Tokenized BlackRock iShares Short Treasury Bond ETF. Multi-chain, daily NAV updates, KYC required.",
        "tags": ["institutional", "treasury", "multi-chain", "accredited"],
    },
    {
        "id": "OMMF",
        "name": "Ondo US Money Market Fund",
        "category": "Government Bonds",
        "subcategory": "Money Market",
        "chain": "Ethereum",
        "protocol": "Ondo Finance",
        "token_symbol": "OMMF",
        "coingecko_id": None,
        "defillama_slug": "ondo-finance",
        "expected_yield_pct": 4.95,
        "risk_score": 1,
        "liquidity_score": 9,
        "regulatory_score": 9,
        "min_investment_usd": 100_000,
        "inception_date": "2023-06-01",
        "description": "Tokenized US money market fund. Holds overnight repos and T-bills. 1:1 USD redeemable.",
        "tags": ["institutional", "money-market", "accredited"],
    },
    {
        "id": "USDM",
        "name": "Mountain Protocol USD",
        "category": "Government Bonds",
        "subcategory": "Yield Stablecoin",
        "chain": "Ethereum / Polygon",
        "protocol": "Mountain Protocol",
        "token_symbol": "USDM",
        "coingecko_id": "usdm",
        "defillama_slug": "mountain-protocol",
        "expected_yield_pct": 4.90,
        "risk_score": 2,
        "liquidity_score": 10,
        "regulatory_score": 8,
        "min_investment_usd": 1,
        "inception_date": "2023-09-01",
        "description": "Yield-bearing stablecoin backed by T-bills. Rebasing token — balance grows daily. Bermuda-regulated.",
        "tags": ["retail", "stablecoin", "treasury", "yield-bearing", "rebasing"],
    },
    {
        "id": "USDY",
        "name": "Ondo US Dollar Yield Token",
        "category": "Government Bonds",
        "subcategory": "Yield Stablecoin",
        "chain": "Ethereum / Solana / Mantle",
        "protocol": "Ondo Finance",
        "token_symbol": "USDY",
        "coingecko_id": "ondo-us-dollar-yield",
        "defillama_slug": "ondo-finance",
        "expected_yield_pct": 5.00,
        "risk_score": 2,
        "liquidity_score": 10,
        "regulatory_score": 8,
        "min_investment_usd": 500,
        "inception_date": "2023-08-01",
        "description": "Tokenized note backed by US bank demand deposits and Treasuries. Transferable after 40-day lockup.",
        "tags": ["retail", "stablecoin", "treasury", "yield-bearing"],
    },
    {
        "id": "STBT",
        "name": "Short-term Treasury Bill Token",
        "category": "Government Bonds",
        "subcategory": "US Treasury",
        "chain": "Ethereum",
        "protocol": "Matrixport / Parallel Finance",
        "token_symbol": "STBT",
        "coingecko_id": "stbt",
        "defillama_slug": "matrixport",
        "expected_yield_pct": 4.85,
        "risk_score": 2,
        "liquidity_score": 7,
        "regulatory_score": 7,
        "min_investment_usd": 100_000,
        "inception_date": "2023-03-01",
        "description": "6-month T-bill backed token by Matrixport. Used as DeFi collateral on Curve/Crvusd.",
        "tags": ["institutional", "treasury", "defi-collateral"],
    },

    # ── PRIVATE CREDIT / DEBT ────────────────────────────────────────────────
    {
        "id": "MAPLE_USDC",
        "name": "Maple Finance Cash Management Pool",
        "category": "Private Credit",
        "subcategory": "Cash Management",
        "chain": "Ethereum / Solana",
        "protocol": "Maple Finance",
        "token_symbol": "MPL",
        "coingecko_id": "maple",
        "defillama_slug": "maple",
        "expected_yield_pct": 8.50,
        "risk_score": 4,
        "liquidity_score": 7,
        "regulatory_score": 7,
        "min_investment_usd": 50_000,
        "inception_date": "2021-06-01",
        "description": "Institutional lending pools for accredited borrowers. Senior secured, overcollateralized positions.",
        "tags": ["institutional", "private-credit", "lending", "accredited"],
    },
    {
        "id": "MAPLE_HIGH_YIELD",
        "name": "Maple Finance High Yield Secured Lending",
        "category": "Private Credit",
        "subcategory": "High Yield",
        "chain": "Ethereum",
        "protocol": "Maple Finance",
        "token_symbol": "MPL",
        "coingecko_id": "maple",
        "defillama_slug": "maple",
        "expected_yield_pct": 12.50,
        "risk_score": 6,
        "liquidity_score": 5,
        "regulatory_score": 7,
        "min_investment_usd": 100_000,
        "inception_date": "2022-01-01",
        "description": "Higher-yield pools targeting emerging market borrowers and growth-stage crypto companies.",
        "tags": ["institutional", "high-yield", "private-credit", "accredited"],
    },
    {
        "id": "GFI_SENIOR",
        "name": "Goldfinch Senior Pool",
        "category": "Private Credit",
        "subcategory": "Emerging Market Loans",
        "chain": "Ethereum",
        "protocol": "Goldfinch",
        "token_symbol": "GFI",
        "coingecko_id": "goldfinch",
        "defillama_slug": "goldfinch",
        "expected_yield_pct": 8.00,
        "risk_score": 5,
        "liquidity_score": 6,
        "regulatory_score": 7,
        "min_investment_usd": 0,
        "inception_date": "2021-01-01",
        "description": "Automated senior pool lending to emerging market borrowers (India, SE Asia, Africa). Auto-diversified.",
        "tags": ["retail", "private-credit", "emerging-markets", "senior"],
    },
    {
        "id": "GFI_TRANCHED",
        "name": "Goldfinch Tranched Pools",
        "category": "Private Credit",
        "subcategory": "Emerging Market Loans",
        "chain": "Ethereum",
        "protocol": "Goldfinch",
        "token_symbol": "GFI",
        "coingecko_id": "goldfinch",
        "defillama_slug": "goldfinch",
        "expected_yield_pct": 14.00,
        "risk_score": 7,
        "liquidity_score": 4,
        "regulatory_score": 6,
        "min_investment_usd": 0,
        "inception_date": "2021-06-01",
        "description": "Junior tranche pools with higher yield. Absorbs first-loss risk from senior pool capital.",
        "tags": ["retail", "private-credit", "emerging-markets", "junior", "high-yield"],
    },
    {
        "id": "TRUEFI_SECURED",
        "name": "TrueFi Secured Lending",
        "category": "Private Credit",
        "subcategory": "Secured Loans",
        "chain": "Ethereum / Optimism",
        "protocol": "TrueFi",
        "token_symbol": "TRU",
        "coingecko_id": "truefi",
        "defillama_slug": "truefi",
        "expected_yield_pct": 9.50,
        "risk_score": 5,
        "liquidity_score": 6,
        "regulatory_score": 7,
        "min_investment_usd": 0,
        "inception_date": "2020-11-01",
        "description": "On-chain credit rating system for institutional borrowers. Community-voted credit decisions.",
        "tags": ["institutional", "private-credit", "secured", "credit-scoring"],
    },
    {
        "id": "CFG_TINLAKE",
        "name": "Centrifuge Tinlake Asset Pools",
        "category": "Private Credit",
        "subcategory": "Trade Finance / Invoices",
        "chain": "Ethereum / Centrifuge Chain",
        "protocol": "Centrifuge",
        "token_symbol": "CFG",
        "coingecko_id": "centrifuge",
        "defillama_slug": "centrifuge",
        "expected_yield_pct": 10.50,
        "risk_score": 5,
        "liquidity_score": 5,
        "regulatory_score": 7,
        "min_investment_usd": 0,
        "inception_date": "2021-05-01",
        "description": "NFT-backed real-world loan pools. Asset types: freight invoices, US real estate bridge loans, consumer credit.",
        "tags": ["retail", "private-credit", "trade-finance", "invoices", "nft"],
    },
    {
        "id": "ARCA_DIGITAL",
        "name": "Arca US Treasury Fund",
        "category": "Private Credit",
        "subcategory": "Treasury + Credit",
        "chain": "Ethereum",
        "protocol": "Arca",
        "token_symbol": "ArCoin",
        "coingecko_id": None,
        "defillama_slug": None,
        "expected_yield_pct": 5.50,
        "risk_score": 3,
        "liquidity_score": 6,
        "regulatory_score": 9,
        "min_investment_usd": 1_000,
        "inception_date": "2020-07-01",
        "description": "SEC-registered digital fund combining US Treasuries with a small credit allocation. Daily NAV.",
        "tags": ["institutional", "treasury", "credit-blend", "registered-fund"],
    },

    # ── REAL ESTATE ──────────────────────────────────────────────────────────
    {
        "id": "REALT_RES",
        "name": "RealT Residential Rental Properties",
        "category": "Real Estate",
        "subcategory": "Residential Rental",
        "chain": "Ethereum / Gnosis",
        "protocol": "RealT",
        "token_symbol": "REALT",
        "coingecko_id": None,
        "defillama_slug": None,
        "expected_yield_pct": 8.50,
        "risk_score": 5,
        "liquidity_score": 4,
        "regulatory_score": 7,
        "min_investment_usd": 50,
        "inception_date": "2019-10-01",
        "description": "Fractional US residential real estate. Rental income paid weekly in xDAI. Properties in Detroit, Chicago, Cleveland.",
        "tags": ["retail", "real-estate", "residential", "rental-income", "fractional"],
    },
    {
        "id": "LOFTY_RES",
        "name": "Lofty.ai Tokenized Rental Properties",
        "category": "Real Estate",
        "subcategory": "Residential Rental",
        "chain": "Algorand",
        "protocol": "Lofty.ai",
        "token_symbol": "LOFTY",
        "coingecko_id": None,
        "defillama_slug": None,
        "expected_yield_pct": 7.50,
        "risk_score": 5,
        "liquidity_score": 5,
        "regulatory_score": 8,
        "min_investment_usd": 50,
        "inception_date": "2021-04-01",
        "description": "Algorand-based fractional real estate. 100+ US properties, daily rent payouts, secondary market trading.",
        "tags": ["retail", "real-estate", "residential", "rental-income", "algorand"],
    },
    {
        "id": "TANGIBLE_USDR",
        "name": "Tangible USDR - Real Estate Stablecoin",
        "category": "Real Estate",
        "subcategory": "Real Estate Stablecoin",
        "chain": "Polygon",
        "protocol": "Tangible",
        "token_symbol": "USDR",
        "coingecko_id": "real-usd",
        "defillama_slug": "tangible",
        "expected_yield_pct": 8.00,
        "risk_score": 6,
        "liquidity_score": 7,
        "regulatory_score": 6,
        "min_investment_usd": 1,
        "inception_date": "2022-10-01",
        "description": "Stablecoin backed by tokenized UK real estate + TNGBL token insurance fund. Yield from rental income.",
        "tags": ["retail", "real-estate", "stablecoin", "yield-bearing", "uk"],
    },
    {
        "id": "PARCL",
        "name": "Parcl Real Estate Index",
        "category": "Real Estate",
        "subcategory": "Real Estate Index",
        "chain": "Solana",
        "protocol": "Parcl",
        "token_symbol": "PARCL",
        "coingecko_id": "parcl",
        "defillama_slug": "parcl",
        "expected_yield_pct": 12.00,
        "risk_score": 7,
        "liquidity_score": 8,
        "regulatory_score": 6,
        "min_investment_usd": 10,
        "inception_date": "2023-03-01",
        "description": "Synthetic real estate indices on Solana. Go long/short on NYC, Miami, LA, SF real estate price indices.",
        "tags": ["retail", "real-estate", "synthetic", "index", "leverage"],
    },
    {
        "id": "PROPY",
        "name": "Propy Real Estate NFT Titles",
        "category": "Real Estate",
        "subcategory": "Title / Deed NFT",
        "chain": "Ethereum / Polygon",
        "protocol": "Propy",
        "token_symbol": "PRO",
        "coingecko_id": "propy",
        "defillama_slug": None,
        "expected_yield_pct": 6.00,
        "risk_score": 6,
        "liquidity_score": 4,
        "regulatory_score": 8,
        "min_investment_usd": 1_000,
        "inception_date": "2017-01-01",
        "description": "Blockchain property titles and real estate NFT marketplacen. US + international properties.",
        "tags": ["retail", "real-estate", "title-nft", "marketplace"],
    },
    {
        "id": "LANDSHARES",
        "name": "Landshares Farmland Tokens",
        "category": "Real Estate",
        "subcategory": "Agricultural Land",
        "chain": "Ethereum",
        "protocol": "Landshares",
        "token_symbol": "LANS",
        "coingecko_id": None,
        "defillama_slug": None,
        "expected_yield_pct": 6.50,
        "risk_score": 4,
        "liquidity_score": 3,
        "regulatory_score": 7,
        "min_investment_usd": 100,
        "inception_date": "2022-06-01",
        "description": "Fractional US farmland ownership. Passive income from crop leases + land appreciation.",
        "tags": ["retail", "real-estate", "farmland", "agriculture"],
    },
    {
        "id": "BLOCKS_COM",
        "name": "Blocksquare Commercial Real Estate",
        "category": "Real Estate",
        "subcategory": "Commercial",
        "chain": "Ethereum",
        "protocol": "Blocksquare",
        "token_symbol": "BST",
        "coingecko_id": "blocksquare",
        "defillama_slug": None,
        "expected_yield_pct": 7.00,
        "risk_score": 5,
        "liquidity_score": 4,
        "regulatory_score": 7,
        "min_investment_usd": 100,
        "inception_date": "2020-01-01",
        "description": "European commercial property tokenization platform. Hotels, offices, retail spaces.",
        "tags": ["retail", "real-estate", "commercial", "europe"],
    },
    {
        "id": "DIGISHARES",
        "name": "DigiShares Real Estate Tokenization",
        "category": "Real Estate",
        "subcategory": "Commercial / Residential",
        "chain": "Ethereum / BSC",
        "protocol": "DigiShares",
        "token_symbol": "DGS",
        "coingecko_id": "digishares",
        "defillama_slug": None,
        "expected_yield_pct": 7.50,
        "risk_score": 5,
        "liquidity_score": 4,
        "regulatory_score": 7,
        "min_investment_usd": 500,
        "inception_date": "2019-01-01",
        "description": "White-label tokenization platform for real estate developers. Global coverage.",
        "tags": ["retail", "real-estate", "white-label", "global"],
    },

    # ── COMMODITIES ──────────────────────────────────────────────────────────
    {
        "id": "PAXG",
        "name": "Pax Gold",
        "category": "Commodities",
        "subcategory": "Gold",
        "chain": "Ethereum",
        "protocol": "Paxos",
        "token_symbol": "PAXG",
        "coingecko_id": "pax-gold",
        "defillama_slug": None,
        "expected_yield_pct": 0.0,
        "risk_score": 2,
        "liquidity_score": 9,
        "regulatory_score": 9,
        "min_investment_usd": 1,
        "inception_date": "2019-09-01",
        "description": "Each PAXG = 1 fine troy oz of gold in LBMA-accredited vaults. Redeemable for physical gold. NYDFS regulated.",
        "tags": ["retail", "gold", "commodity", "store-of-value", "nydfs"],
    },
    {
        "id": "XAUT",
        "name": "Tether Gold",
        "category": "Commodities",
        "subcategory": "Gold",
        "chain": "Ethereum / Tron",
        "protocol": "Tether",
        "token_symbol": "XAUt",
        "coingecko_id": "tether-gold",
        "defillama_slug": None,
        "expected_yield_pct": 0.0,
        "risk_score": 3,
        "liquidity_score": 9,
        "regulatory_score": 7,
        "min_investment_usd": 1,
        "inception_date": "2020-01-01",
        "description": "Gold-backed token by Tether. Each token = 1 troy fine ounce on specific gold bars in Switzerland.",
        "tags": ["retail", "gold", "commodity", "tether"],
    },
    {
        "id": "CACHE_GOLD",
        "name": "Cache Gold Token",
        "category": "Commodities",
        "subcategory": "Gold",
        "chain": "Ethereum",
        "protocol": "Cache Gold",
        "token_symbol": "CGT",
        "coingecko_id": "cache-gold",
        "defillama_slug": None,
        "expected_yield_pct": 0.0,
        "risk_score": 3,
        "liquidity_score": 6,
        "regulatory_score": 7,
        "min_investment_usd": 1,
        "inception_date": "2019-01-01",
        "description": "Physical gold stored in Singapore FreePort. Each CGT = 1 gram of gold. Storage fee applies.",
        "tags": ["retail", "gold", "commodity", "singapore"],
    },
    {
        "id": "BACKED_SILVER",
        "name": "Backed Silver",
        "category": "Commodities",
        "subcategory": "Silver",
        "chain": "Ethereum",
        "protocol": "Backed Finance",
        "token_symbol": "bXAG",
        "coingecko_id": None,
        "defillama_slug": "backed-finance",
        "expected_yield_pct": 0.0,
        "risk_score": 4,
        "liquidity_score": 6,
        "regulatory_score": 7,
        "min_investment_usd": 1,
        "inception_date": "2022-01-01",
        "description": "Tokenized silver-backed ETC. Physical silver stored in Swiss vaults. Backed by iShares Silver Trust.",
        "tags": ["retail", "silver", "commodity", "swiss"],
    },
    {
        "id": "BACKED_OIL",
        "name": "Backed Oil",
        "category": "Commodities",
        "subcategory": "Energy",
        "chain": "Ethereum",
        "protocol": "Backed Finance",
        "token_symbol": "bOIL",
        "coingecko_id": None,
        "defillama_slug": "backed-finance",
        "expected_yield_pct": 0.0,
        "risk_score": 7,
        "liquidity_score": 6,
        "regulatory_score": 6,
        "min_investment_usd": 1,
        "inception_date": "2022-06-01",
        "description": "Tokenized crude oil exposure backed by ProShares Ultra DJ-AIG Crude Oil ETF.",
        "tags": ["retail", "oil", "commodity", "energy"],
    },

    # ── CORPORATE BONDS / FIXED INCOME ──────────────────────────────────────
    {
        "id": "BACKED_AAPL",
        "name": "Backed Finance Apple Bond",
        "category": "Corporate Bonds",
        "subcategory": "Investment Grade",
        "chain": "Ethereum",
        "protocol": "Backed Finance",
        "token_symbol": "bCSPX",
        "coingecko_id": None,
        "defillama_slug": "backed-finance",
        "expected_yield_pct": 4.50,
        "risk_score": 3,
        "liquidity_score": 7,
        "regulatory_score": 8,
        "min_investment_usd": 1,
        "inception_date": "2021-12-01",
        "description": "Tokenized corporate bond ETF (iShares Core S&P 500 Tracker). Swiss-regulated, 1:1 backing.",
        "tags": ["retail", "corporate-bond", "etf", "ig", "swiss"],
    },
    {
        "id": "BACKED_CSPX",
        "name": "Backed S&P 500 Tracker",
        "category": "Equities",
        "subcategory": "Index",
        "chain": "Ethereum / Gnosis",
        "protocol": "Backed Finance",
        "token_symbol": "bCSPX",
        "coingecko_id": "backed-cspx",
        "defillama_slug": "backed-finance",
        "expected_yield_pct": 10.0,
        "risk_score": 5,
        "liquidity_score": 7,
        "regulatory_score": 8,
        "min_investment_usd": 1,
        "inception_date": "2022-03-01",
        "description": "Tokenized S&P 500 ETF exposure on-chain. FINMA-supervised. Non-US investors only.",
        "tags": ["retail", "equities", "sp500", "index", "swiss"],
    },
    {
        "id": "SWARM_TSLA",
        "name": "Swarm Tesla Stock Token",
        "category": "Equities",
        "subcategory": "Single Stock",
        "chain": "Polygon",
        "protocol": "Swarm Markets",
        "token_symbol": "sTSLA",
        "coingecko_id": None,
        "defillama_slug": "swarm",
        "expected_yield_pct": 0.0,
        "risk_score": 8,
        "liquidity_score": 7,
        "regulatory_score": 8,
        "min_investment_usd": 1,
        "inception_date": "2021-11-01",
        "description": "Fully-backed tokenized TSLA shares on Polygon. BaFin-licensed. 24/7 trading vs T+2 settlement.",
        "tags": ["retail", "equities", "single-stock", "bafin", "germany"],
    },
    {
        "id": "SWARM_AAPL",
        "name": "Swarm Apple Stock Token",
        "category": "Equities",
        "subcategory": "Single Stock",
        "chain": "Polygon",
        "protocol": "Swarm Markets",
        "token_symbol": "sAAPL",
        "coingecko_id": None,
        "defillama_slug": "swarm",
        "expected_yield_pct": 0.0,
        "risk_score": 6,
        "liquidity_score": 7,
        "regulatory_score": 8,
        "min_investment_usd": 1,
        "inception_date": "2021-11-01",
        "description": "Fully-backed tokenized AAPL shares. BaFin-licensed, fully regulated German marketplace.",
        "tags": ["retail", "equities", "single-stock", "bafin", "germany"],
    },

    # ── INFRASTRUCTURE ───────────────────────────────────────────────────────
    {
        "id": "ENERGYFI",
        "name": "EnergyFi Solar Infrastructure",
        "category": "Infrastructure",
        "subcategory": "Renewable Energy",
        "chain": "Ethereum",
        "protocol": "EnergyFi",
        "token_symbol": "EFI",
        "coingecko_id": None,
        "defillama_slug": None,
        "expected_yield_pct": 9.00,
        "risk_score": 5,
        "liquidity_score": 4,
        "regulatory_score": 6,
        "min_investment_usd": 500,
        "inception_date": "2022-05-01",
        "description": "Tokenized solar energy infrastructure. Revenue from energy sales creates on-chain yield.",
        "tags": ["retail", "infrastructure", "solar", "green-energy"],
    },
    {
        "id": "ONDO_INFRA",
        "name": "Infrastructure Debt Fund",
        "category": "Infrastructure",
        "subcategory": "Infrastructure Debt",
        "chain": "Ethereum",
        "protocol": "Ondo Finance",
        "token_symbol": "ONDO",
        "coingecko_id": "ondo-finance",
        "defillama_slug": "ondo-finance",
        "expected_yield_pct": 7.50,
        "risk_score": 4,
        "liquidity_score": 5,
        "regulatory_score": 8,
        "min_investment_usd": 100_000,
        "inception_date": "2023-12-01",
        "description": "Senior secured infrastructure debt in transportation, utilities, and social infrastructure.",
        "tags": ["institutional", "infrastructure", "senior-secured", "debt"],
    },

    # ── CARBON CREDITS ───────────────────────────────────────────────────────
    {
        "id": "MCO2",
        "name": "Moss.Earth Carbon Credit Token",
        "category": "Carbon Credits",
        "subcategory": "Voluntary Carbon Market",
        "chain": "Ethereum / Polygon",
        "protocol": "Moss.Earth",
        "token_symbol": "MCO2",
        "coingecko_id": "moss-carbon-credit",
        "defillama_slug": None,
        "expected_yield_pct": 0.0,
        "risk_score": 7,
        "liquidity_score": 7,
        "regulatory_score": 6,
        "min_investment_usd": 1,
        "inception_date": "2020-08-01",
        "description": "Each MCO2 = 1 tonne CO2 offset from Amazon rainforest preservation projects. VCS certified.",
        "tags": ["retail", "carbon-credit", "amazon", "vcs", "voluntary"],
    },
    {
        "id": "NBO",
        "name": "Toucan Protocol Nature Carbon Tonne",
        "category": "Carbon Credits",
        "subcategory": "Nature-Based",
        "chain": "Polygon",
        "protocol": "Toucan Protocol",
        "token_symbol": "NCT",
        "coingecko_id": "toucan-protocol-nature-carbon-tonne",
        "defillama_slug": "toucan",
        "expected_yield_pct": 0.0,
        "risk_score": 8,
        "liquidity_score": 8,
        "regulatory_score": 5,
        "min_investment_usd": 1,
        "inception_date": "2021-10-01",
        "description": "Pool of Verra-certified nature-based carbon credits on Polygon. Tradeable DeFi carbon pool.",
        "tags": ["retail", "carbon-credit", "nature-based", "toucan", "defi-native"],
    },
    {
        "id": "KLIMA",
        "name": "KlimaDAO Carbon Treasury",
        "category": "Carbon Credits",
        "subcategory": "Carbon Treasury",
        "chain": "Polygon",
        "protocol": "KlimaDAO",
        "token_symbol": "KLIMA",
        "coingecko_id": "klima-dao",
        "defillama_slug": "klimadao",
        "expected_yield_pct": 5.00,
        "risk_score": 8,
        "liquidity_score": 8,
        "regulatory_score": 5,
        "min_investment_usd": 1,
        "inception_date": "2021-10-18",
        "description": "DAO governing a treasury of tokenized carbon offsets. Staking yields paid in KLIMA.",
        "tags": ["retail", "carbon-credit", "dao", "staking", "treasury"],
    },

    # ── INTELLECTUAL PROPERTY / ROYALTIES ────────────────────────────────────
    {
        "id": "ROYAL_MUSIC",
        "name": "Royal Music Royalty Tokens",
        "category": "Intellectual Property",
        "subcategory": "Music Royalties",
        "chain": "Ethereum",
        "protocol": "Royal",
        "token_symbol": "LDA",
        "coingecko_id": None,
        "defillama_slug": None,
        "expected_yield_pct": 6.50,
        "risk_score": 6,
        "liquidity_score": 4,
        "regulatory_score": 7,
        "min_investment_usd": 100,
        "inception_date": "2021-11-01",
        "description": "Fractional music streaming royalties from artists like Nas, The Chainsmokers, Kygo.",
        "tags": ["retail", "music-royalties", "ip", "streaming"],
    },
    {
        "id": "OPULOUS",
        "name": "Opulous Music IP Tokens",
        "category": "Intellectual Property",
        "subcategory": "Music Royalties",
        "chain": "Algorand",
        "protocol": "Opulous",
        "token_symbol": "OPUL",
        "coingecko_id": "opulous",
        "defillama_slug": None,
        "expected_yield_pct": 8.00,
        "risk_score": 7,
        "liquidity_score": 5,
        "regulatory_score": 7,
        "min_investment_usd": 100,
        "inception_date": "2021-07-01",
        "description": "Music copyright-backed DeFi loans and fractional royalty tokens on Algorand.",
        "tags": ["retail", "music-royalties", "ip", "algorand", "defi"],
    },

    # ── ART & COLLECTIBLES ───────────────────────────────────────────────────
    {
        "id": "MASTERWORKS",
        "name": "Masterworks Fine Art Shares",
        "category": "Art & Collectibles",
        "subcategory": "Fine Art",
        "chain": "Off-chain / Reg A+",
        "protocol": "Masterworks",
        "token_symbol": "ART",
        "coingecko_id": None,
        "defillama_slug": None,
        "expected_yield_pct": 14.0,
        "risk_score": 7,
        "liquidity_score": 3,
        "regulatory_score": 9,
        "min_investment_usd": 500,
        "inception_date": "2017-01-01",
        "description": "SEC-qualified shares in authenticated blue-chip art (Banksy, Basquiat, Picasso). Average 14.1% annualized.",
        "tags": ["retail", "fine-art", "collectibles", "sec-reg-a", "illiquid"],
    },
    {
        "id": "FREEPORT_ART",
        "name": "Freeport Fractional Art",
        "category": "Art & Collectibles",
        "subcategory": "Fine Art",
        "chain": "Ethereum",
        "protocol": "Freeport",
        "token_symbol": "FREEPORT",
        "coingecko_id": None,
        "defillama_slug": None,
        "expected_yield_pct": 10.0,
        "risk_score": 8,
        "liquidity_score": 3,
        "regulatory_score": 7,
        "min_investment_usd": 100,
        "inception_date": "2022-01-01",
        "description": "Tokenized fractional ownership of physical art stored in climate-controlled vaults.",
        "tags": ["retail", "fine-art", "fractional", "nft"],
    },

    # ── PRIVATE EQUITY ───────────────────────────────────────────────────────
    {
        "id": "FORGE_EQUITY",
        "name": "Forge Private Market Equity",
        "category": "Private Equity",
        "subcategory": "Pre-IPO / Secondary",
        "chain": "Ethereum",
        "protocol": "Forge Global / INX",
        "token_symbol": "INX",
        "coingecko_id": "inx-token",
        "defillama_slug": None,
        "expected_yield_pct": 20.0,
        "risk_score": 8,
        "liquidity_score": 4,
        "regulatory_score": 8,
        "min_investment_usd": 1_000,
        "inception_date": "2021-09-01",
        "description": "Tokenized pre-IPO and secondary market private equity. Access to Stripe, SpaceX, Databricks-type deals.",
        "tags": ["institutional", "private-equity", "pre-ipo", "secondary"],
    },
    {
        "id": "ADDX_PE",
        "name": "ADDX Private Equity Funds",
        "category": "Private Equity",
        "subcategory": "Fund of Funds",
        "chain": "Ethereum",
        "protocol": "ADDX",
        "token_symbol": "ADDX",
        "coingecko_id": None,
        "defillama_slug": None,
        "expected_yield_pct": 15.0,
        "risk_score": 7,
        "liquidity_score": 4,
        "regulatory_score": 9,
        "min_investment_usd": 10_000,
        "inception_date": "2020-01-01",
        "description": "MAS-licensed Singapore exchange for tokenized PE funds, hedge funds, and private credit.",
        "tags": ["institutional", "private-equity", "singapore", "mas-licensed"],
    },

    # ── INSURANCE & ALTERNATIVE RISK ─────────────────────────────────────────
    {
        "id": "NEXUS_MUTUAL",
        "name": "Nexus Mutual Risk Pools",
        "category": "Insurance",
        "subcategory": "DeFi Risk Cover",
        "chain": "Ethereum",
        "protocol": "Nexus Mutual",
        "token_symbol": "NXM",
        "coingecko_id": "nexus-mutual",
        "defillama_slug": "nexus-mutual",
        "expected_yield_pct": 15.0,
        "risk_score": 8,
        "liquidity_score": 7,
        "regulatory_score": 6,
        "min_investment_usd": 100,
        "inception_date": "2019-05-23",
        "description": "Decentralized mutual insurance protocol. Stake NXM to underwrite covers, earn assessment rewards.",
        "tags": ["retail", "insurance", "defi-cover", "mutual"],
    },
    {
        "id": "RISK_HARBOR",
        "name": "Risk Harbor Structured Insurance",
        "category": "Insurance",
        "subcategory": "Protocol Insurance",
        "chain": "Ethereum",
        "protocol": "Risk Harbor",
        "token_symbol": "HARBOR",
        "coingecko_id": None,
        "defillama_slug": None,
        "expected_yield_pct": 12.0,
        "risk_score": 7,
        "liquidity_score": 5,
        "regulatory_score": 5,
        "min_investment_usd": 1_000,
        "inception_date": "2021-07-01",
        "description": "Automated smart contract insurance using actuarial models instead of human voting.",
        "tags": ["institutional", "insurance", "automated", "protocol-cover"],
    },

    # ── SUPPLY CHAIN / TRADE FINANCE ─────────────────────────────────────────
    {
        "id": "CREDIX_TRADE",
        "name": "Credix Trade Finance Pools",
        "category": "Trade Finance",
        "subcategory": "LatAm Trade Finance",
        "chain": "Solana",
        "protocol": "Credix",
        "token_symbol": "CREDIX",
        "coingecko_id": "credix-finance",
        "defillama_slug": "credix",
        "expected_yield_pct": 14.0,
        "risk_score": 6,
        "liquidity_score": 5,
        "regulatory_score": 7,
        "min_investment_usd": 100_000,
        "inception_date": "2022-01-01",
        "description": "Institutional credit marketplace on Solana. LatAm B2B trade finance, working capital loans.",
        "tags": ["institutional", "trade-finance", "latam", "solana", "private-credit"],
    },
    {
        "id": "POLYTRADE",
        "name": "Polytrade Invoice Financing",
        "category": "Trade Finance",
        "subcategory": "Invoice Financing",
        "chain": "Polygon",
        "protocol": "Polytrade",
        "token_symbol": "TRADE",
        "coingecko_id": "polytrade",
        "defillama_slug": None,
        "expected_yield_pct": 10.0,
        "risk_score": 6,
        "liquidity_score": 5,
        "regulatory_score": 7,
        "min_investment_usd": 1_000,
        "inception_date": "2021-10-01",
        "description": "Invoice financing using USDC. Invoices from Fortune 500 companies as collateral.",
        "tags": ["retail", "trade-finance", "invoice", "polygon"],
    },

    # ── MAKER DAO RWA VAULTS ──────────────────────────────────────────────────
    {
        "id": "MKR_RWA",
        "name": "MakerDAO RWA Vaults",
        "category": "Private Credit",
        "subcategory": "Institutional RWA Vaults",
        "chain": "Ethereum",
        "protocol": "MakerDAO / Sky",
        "token_symbol": "MKR",
        "coingecko_id": "maker",
        "defillama_slug": "makerdao",
        "expected_yield_pct": 5.80,
        "risk_score": 3,
        "liquidity_score": 8,
        "regulatory_score": 7,
        "min_investment_usd": 1,
        "inception_date": "2022-04-01",
        "description": "MakerDAO's off-chain collateral vaults holding T-bills, corporate bonds, and real estate. Backing DAI stablecoin.",
        "tags": ["institutional", "private-credit", "makerdao", "dai-backing"],
    },

    # ── HASHNOTE — Largest institutional T-bill token ────────────────────────
    {
        "id": "USYC",
        "name": "Hashnote US Yield Coin",
        "category": "Government Bonds",
        "subcategory": "US Treasury",
        "chain": "Ethereum",
        "protocol": "Hashnote",
        "token_symbol": "USYC",
        "coingecko_id": None,
        "defillama_slug": "hashnote",
        "expected_yield_pct": 5.10,
        "risk_score": 1,
        "liquidity_score": 8,
        "regulatory_score": 9,
        "min_investment_usd": 100_000,
        "inception_date": "2023-10-01",
        "description": "DRW/Cumberland-backed institutional T-bill fund. One of the top 3 tokenized treasury vehicles by TVL ($500M–$1B).",
        "tags": ["institutional", "treasury", "drw", "cumberland", "accredited"],
    },
    {
        "id": "USCC",
        "name": "Superstate Crypto Carry Fund",
        "category": "Private Credit",
        "subcategory": "Crypto Carry",
        "chain": "Ethereum",
        "protocol": "Superstate",
        "token_symbol": "USCC",
        "coingecko_id": None,
        "defillama_slug": "superstate",
        "expected_yield_pct": 9.00,
        "risk_score": 4,
        "liquidity_score": 7,
        "regulatory_score": 8,
        "min_investment_usd": 100_000,
        "inception_date": "2024-06-01",
        "description": "Tokenized fund capturing crypto carry premium (perpetual funding rates, basis). Higher yield vs pure T-bill.",
        "tags": ["institutional", "carry-trade", "crypto-basis", "superstate"],
    },
    {
        "id": "CLEARPOOL_USDC",
        "name": "Clearpool Institutional Credit Pools",
        "category": "Private Credit",
        "subcategory": "Unsecured Institutional",
        "chain": "Ethereum / Polygon / Arbitrum / Optimism",
        "protocol": "Clearpool",
        "token_symbol": "CPOOL",
        "coingecko_id": "clearpool",
        "defillama_slug": "clearpool",
        "expected_yield_pct": 9.50,
        "risk_score": 6,
        "liquidity_score": 7,
        "regulatory_score": 7,
        "min_investment_usd": 0,
        "inception_date": "2022-03-01",
        "description": "Permissionless single-borrower pools for institutional unsecured credit. Dynamic interest via utilization curve.",
        "tags": ["retail", "private-credit", "unsecured", "multi-chain"],
    },
    {
        "id": "FLOWCARBON_GNT",
        "name": "Flowcarbon Goodness Nature Token",
        "category": "Carbon Credits",
        "subcategory": "Nature-Based",
        "chain": "Polygon",
        "protocol": "Flowcarbon",
        "token_symbol": "GNT",
        "coingecko_id": "flowcarbon",
        "defillama_slug": None,
        "expected_yield_pct": 0.0,
        "risk_score": 8,
        "liquidity_score": 5,
        "regulatory_score": 6,
        "min_investment_usd": 1,
        "inception_date": "2022-05-01",
        "description": "a16z + Samsung-backed nature-based carbon credits on Polygon. VCS and Gold Standard certified offsets.",
        "tags": ["retail", "carbon-credit", "nature-based", "a16z", "vcs"],
    },
    {
        "id": "BACKED_IBTA",
        "name": "Backed US Treasury Bond ETF Token",
        "category": "Government Bonds",
        "subcategory": "US Treasury",
        "chain": "Ethereum / Gnosis",
        "protocol": "Backed Finance",
        "token_symbol": "bIBTA",
        "coingecko_id": None,
        "defillama_slug": "backed-finance",
        "expected_yield_pct": 4.80,
        "risk_score": 1,
        "liquidity_score": 7,
        "regulatory_score": 8,
        "min_investment_usd": 1,
        "inception_date": "2022-09-01",
        "description": "Tokenized iShares USD Treasury Bond 1-3yr ETF (bIBTA). Swiss FINMA-supervised. Non-US investors.",
        "tags": ["retail", "treasury", "etf", "swiss", "non-us"],
    },
    {
        "id": "AGROTOKEN_SOY",
        "name": "Agrotoken Soy Grain Token",
        "category": "Commodities",
        "subcategory": "Agricultural",
        "chain": "Ethereum / Algorand",
        "protocol": "Agrotoken",
        "token_symbol": "SOYA",
        "coingecko_id": "agrotoken",
        "defillama_slug": None,
        "expected_yield_pct": 0.0,
        "risk_score": 6,
        "liquidity_score": 4,
        "regulatory_score": 6,
        "min_investment_usd": 100,
        "inception_date": "2021-08-01",
        "description": "Argentine soy, corn, and wheat grain tokens used as DeFi collateral by farmers. Pioneer in agri-RWA.",
        "tags": ["retail", "agriculture", "commodity", "argentina", "latam"],
    },
    {
        "id": "ANOTE_MUSIC",
        "name": "ANote Music Publishing Royalties",
        "category": "Intellectual Property",
        "subcategory": "Music Publishing",
        "chain": "Ethereum",
        "protocol": "ANote Music",
        "token_symbol": "ANOTE",
        "coingecko_id": "anote-music",
        "defillama_slug": None,
        "expected_yield_pct": 7.50,
        "risk_score": 6,
        "liquidity_score": 4,
        "regulatory_score": 7,
        "min_investment_usd": 100,
        "inception_date": "2020-06-01",
        "description": "Fractional music publishing rights. Revenue from radio, TV, sync licensing, streaming.",
        "tags": ["retail", "music-royalties", "publishing", "ip", "marketplace"],
    },
    {
        "id": "ENZYME_RWA",
        "name": "Enzyme Finance RWA Vaults",
        "category": "Private Credit",
        "subcategory": "Automated Vault",
        "chain": "Ethereum / Polygon",
        "protocol": "Enzyme Finance",
        "token_symbol": "MLN",
        "coingecko_id": "melon",
        "defillama_slug": "enzyme",
        "expected_yield_pct": 8.00,
        "risk_score": 5,
        "liquidity_score": 7,
        "regulatory_score": 7,
        "min_investment_usd": 0,
        "inception_date": "2019-01-01",
        "description": "On-chain fund management with automated rebalancing. Supports RWA tokens as vault assets.",
        "tags": ["retail", "automated-vault", "fund-management", "defi-native"],
    },
]

# ─────────────────────────────────────────────────────────────────────────────
# PORTFOLIO RISK TIERS
# Each tier: name, description, color, target_yield, max_drawdown, allocations
# allocations: {category: weight_pct} — must sum to 100
# ─────────────────────────────────────────────────────────────────────────────

PORTFOLIO_TIERS = {
    1: {
        "name": "Ultra-Conservative",
        "label": "Shield",
        "color": "#00D4FF",
        "icon": "🛡️",
        "target_yield_pct": 4.5,
        "max_drawdown_pct": 1.0,
        "volatility_pct": 0.5,
        "description": "Capital preservation above all. US government-backed assets only. Sleep well regardless of market conditions.",
        "investor_profile": "Retirees, family offices, institutional treasuries seeking risk-free on-chain yield.",
        "allocations": {
            "Government Bonds": 75,
            "Commodities":      15,
            "Private Credit":    8,
            "Trade Finance":     2,
        },
        "subcategory_bias": ["US Treasury", "Money Market", "Yield Stablecoin", "Gold"],
        "min_risk_score": 1,
        "max_risk_score": 3,
        "rebalance_frequency": "monthly",
    },
    2: {
        "name": "Conservative",
        "label": "Anchor",
        "color": "#34D399",
        "icon": "⚓",
        "target_yield_pct": 7.5,
        "max_drawdown_pct": 5.0,
        "volatility_pct": 2.0,
        "description": "Steady income with minimal downside. High-quality fixed income plus real assets for inflation protection.",
        "investor_profile": "Financial advisors, HNW individuals, pension fund allocators.",
        "allocations": {
            "Government Bonds": 45,
            "Private Credit":   20,
            "Real Estate":      15,
            "Commodities":      15,
            "Carbon Credits":    3,
            "Trade Finance":     2,
        },
        "subcategory_bias": ["US Treasury", "Cash Management", "Residential Rental", "Gold", "Silver"],
        "min_risk_score": 1,
        "max_risk_score": 5,
        "rebalance_frequency": "monthly",
    },
    3: {
        "name": "Moderate",
        "label": "Balance",
        "color": "#FBBF24",
        "icon": "⚖️",
        "target_yield_pct": 11.0,
        "max_drawdown_pct": 15.0,
        "volatility_pct": 5.0,
        "description": "Diversified across all RWA categories. Optimal risk-adjusted return for most investors.",
        "investor_profile": "Sophisticated retail, crypto-native investors, family offices, robo-advisors.",
        "allocations": {
            "Government Bonds": 25,
            "Private Credit":   25,
            "Real Estate":      20,
            "Commodities":      10,
            "Infrastructure":    8,
            "Equities":          6,
            "Carbon Credits":    3,
            "Trade Finance":     3,
        },
        "subcategory_bias": ["US Treasury", "Emerging Market Loans", "Residential Rental", "Gold", "Renewable Energy"],
        "min_risk_score": 2,
        "max_risk_score": 7,
        "rebalance_frequency": "bi-weekly",
    },
    4: {
        "name": "Aggressive",
        "label": "Alpha",
        "color": "#F97316",
        "icon": "🔥",
        "target_yield_pct": 17.0,
        "max_drawdown_pct": 25.0,
        "volatility_pct": 10.0,
        "description": "Higher yield through selective exposure to private equity, high-yield credit, and development real estate.",
        "investor_profile": "Accredited investors, crypto funds, family offices with multi-year horizons.",
        "allocations": {
            "Private Credit":   30,
            "Real Estate":      20,
            "Private Equity":   15,
            "Government Bonds": 10,
            "Infrastructure":   10,
            "Equities":         7,
            "Carbon Credits":   4,
            "Art & Collectibles": 2,
            "Insurance":        2,
        },
        "subcategory_bias": ["High Yield", "Pre-IPO / Secondary", "Commercial", "Infrastructure Debt"],
        "min_risk_score": 4,
        "max_risk_score": 8,
        "rebalance_frequency": "weekly",
    },
    5: {
        "name": "Ultra-Aggressive",
        "label": "Apex",
        "color": "#EF4444",
        "icon": "⚡",
        "target_yield_pct": 25.0,
        "max_drawdown_pct": 40.0,
        "volatility_pct": 20.0,
        "description": "Maximum return pursuit. Emerging market credit, distressed real estate, early-stage private equity, alternative RWAs.",
        "investor_profile": "Professional traders, crypto-native funds, ultra-HNW speculative allocation.",
        "allocations": {
            "Private Credit":   30,
            "Private Equity":   20,
            "Real Estate":      15,
            "Intellectual Property": 10,
            "Art & Collectibles": 8,
            "Carbon Credits":    7,
            "Infrastructure":    5,
            "Insurance":         3,
            "Trade Finance":     2,
        },
        "subcategory_bias": ["Emerging Market Loans", "Pre-IPO / Secondary", "Music Royalties", "Nature-Based", "Renewable Energy"],
        "min_risk_score": 5,
        "max_risk_score": 10,
        "rebalance_frequency": "daily",
    },
}

# ─────────────────────────────────────────────────────────────────────────────
# AI AGENT PROFILES
# Each agent: name, description, risk_tier, max_trade_size_pct, strategy
# ─────────────────────────────────────────────────────────────────────────────

AI_AGENTS = {
    "GUARDIAN": {
        "name": "Guardian AI",
        "description": "Ultra-conservative yield optimizer. Focuses on T-bill rotation and AAA credit quality.",
        "risk_tier": 1,
        "max_trade_size_pct": 5.0,
        "daily_loss_limit_pct": 0.5,
        "strategy": "yield_optimization",
        "rebalance_threshold_pct": 2.0,
        "color": "#00D4FF",
        "icon": "🛡️",
    },
    "NAVIGATOR": {
        "name": "Navigator AI",
        "description": "Conservative income generator. Balances T-bills, investment-grade credit, and real estate yield.",
        "risk_tier": 2,
        "max_trade_size_pct": 8.0,
        "daily_loss_limit_pct": 1.5,
        "strategy": "income_generation",
        "rebalance_threshold_pct": 3.0,
        "color": "#34D399",
        "icon": "⚓",
    },
    "HORIZON": {
        "name": "Horizon AI",
        "description": "Balanced portfolio manager. Multi-asset RWA diversification with MPT optimization.",
        "risk_tier": 3,
        "max_trade_size_pct": 10.0,
        "daily_loss_limit_pct": 3.0,
        "strategy": "mpt_balanced",
        "rebalance_threshold_pct": 5.0,
        "color": "#FBBF24",
        "icon": "⚖️",
    },
    "TITAN": {
        "name": "Titan AI",
        "description": "Aggressive alpha seeker. Targets high-yield private credit, PE, and arbitrage opportunities.",
        "risk_tier": 4,
        "max_trade_size_pct": 15.0,
        "daily_loss_limit_pct": 5.0,
        "strategy": "alpha_generation",
        "rebalance_threshold_pct": 8.0,
        "color": "#F97316",
        "icon": "🔥",
    },
    "APEX": {
        "name": "Apex AI",
        "description": "Maximum return hunter. Deploys across all RWA categories with dynamic risk sizing.",
        "risk_tier": 5,
        "max_trade_size_pct": 25.0,
        "daily_loss_limit_pct": 10.0,
        "strategy": "maximum_return",
        "rebalance_threshold_pct": 10.0,
        "color": "#EF4444",
        "icon": "⚡",
    },
}

# ─────────────────────────────────────────────────────────────────────────────
# DEFILLAMA PROTOCOL SLUGS (for TVL / yield data)
# ─────────────────────────────────────────────────────────────────────────────

DEFILLAMA_PROTOCOLS = [
    "centrifuge", "maple", "goldfinch", "truefi", "ondo-finance",
    "makerdao", "backed-finance", "superstate", "mountain-protocol",
    "klimadao", "toucan", "credix", "polytrade", "nexus-mutual",
    "parcl", "tangible",
]

# ─────────────────────────────────────────────────────────────────────────────
# COINGECKO TOKEN IDS for price feeds
# ─────────────────────────────────────────────────────────────────────────────

COINGECKO_IDS = [
    a["coingecko_id"] for a in RWA_UNIVERSE if a.get("coingecko_id")
]

# ─────────────────────────────────────────────────────────────────────────────
# ASSET CATEGORY COLORS
# ─────────────────────────────────────────────────────────────────────────────

CATEGORY_COLORS = {
    "Government Bonds":     "#00D4FF",
    "Private Credit":       "#34D399",
    "Real Estate":          "#A78BFA",
    "Commodities":          "#FBBF24",
    "Equities":             "#F97316",
    "Infrastructure":       "#06B6D4",
    "Carbon Credits":       "#10B981",
    "Intellectual Property":"#EC4899",
    "Art & Collectibles":   "#8B5CF6",
    "Private Equity":       "#EF4444",
    "Insurance":            "#6366F1",
    "Trade Finance":        "#14B8A6",
}

# ─────────────────────────────────────────────────────────────────────────────
# RISK SCORE LABELS
# ─────────────────────────────────────────────────────────────────────────────

RISK_LABELS = {
    1:  "AAA / Risk-Free",
    2:  "AA / Minimal Risk",
    3:  "A / Very Low Risk",
    4:  "BBB / Low Risk",
    5:  "BB / Moderate Risk",
    6:  "B / Medium-High Risk",
    7:  "CCC / High Risk",
    8:  "CC / Very High Risk",
    9:  "C / Extreme Risk",
    10: "D / Speculative",
}

# ─────────────────────────────────────────────────────────────────────────────
# ARBITRAGE THRESHOLDS
# ─────────────────────────────────────────────────────────────────────────────

ARB_MIN_YIELD_SPREAD_PCT    = 1.0   # minimum yield spread to flag arb opportunity
ARB_MIN_PRICE_SPREAD_PCT    = 0.5   # minimum price spread (vs NAV) to flag
ARB_STRONG_THRESHOLD_PCT    = 3.0   # strong arbitrage threshold
ARB_EXTREME_THRESHOLD_PCT   = 5.0   # extreme/exceptional arbitrage
